// generated by Fast Light User Interface Designer (fluid) version 1.0104

#ifndef LFO4gui_h
#define LFO4gui_h
#include <FL/Fl.H>
#include "PortAudioStuff.h"
#include <FL/Fl_Box.H>
class Fl_DrawShape;
extern void drawWaveform(Fl_DrawShape*);

class Fl_DrawShape : public Fl_Box {
public:
  Fl_DrawShape(int X, int Y, int W, int H, const char *l=0) ;
  float *table;
  long tablen;
  void draw();
};
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Positioner.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Round_Button.H>
#include <FL/Fl_Slider.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Scroll.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Value_Slider.H>

class LFO4gui : public PAstuff {
  bool isCarrier;
public:
  LFO4gui();
  Fl_Double_Window *mainWindow;
  Fl_Positioner *joy;
private:
  inline void cb_joy_i(Fl_Positioner*, void*);
  static void cb_joy(Fl_Positioner*, void*);
  inline void cb_Sine_i(Fl_Round_Button*, void*);
  static void cb_Sine(Fl_Round_Button*, void*);
  inline void cb_Triangle_i(Fl_Round_Button*, void*);
  static void cb_Triangle(Fl_Round_Button*, void*);
  inline void cb_Up_i(Fl_Round_Button*, void*);
  static void cb_Up(Fl_Round_Button*, void*);
  inline void cb_Down_i(Fl_Round_Button*, void*);
  static void cb_Down(Fl_Round_Button*, void*);
  inline void cb_Square_i(Fl_Round_Button*, void*);
  static void cb_Square(Fl_Round_Button*, void*);
  inline void cb_Random_i(Fl_Round_Button*, void*);
  static void cb_Random(Fl_Round_Button*, void*);
  inline void cb_Custom_i(Fl_Round_Button*, void*);
  static void cb_Custom(Fl_Round_Button*, void*);
  inline void cb_Step_i(Fl_Round_Button*, void*);
  static void cb_Step(Fl_Round_Button*, void*);
  inline void cb_Sine1_i(Fl_Round_Button*, void*);
  static void cb_Sine1(Fl_Round_Button*, void*);
  inline void cb_Triangle1_i(Fl_Round_Button*, void*);
  static void cb_Triangle1(Fl_Round_Button*, void*);
  inline void cb_Up1_i(Fl_Round_Button*, void*);
  static void cb_Up1(Fl_Round_Button*, void*);
  inline void cb_Down1_i(Fl_Round_Button*, void*);
  static void cb_Down1(Fl_Round_Button*, void*);
  inline void cb_Square1_i(Fl_Round_Button*, void*);
  static void cb_Square1(Fl_Round_Button*, void*);
  inline void cb_Random1_i(Fl_Round_Button*, void*);
  static void cb_Random1(Fl_Round_Button*, void*);
  inline void cb_Custom1_i(Fl_Round_Button*, void*);
  static void cb_Custom1(Fl_Round_Button*, void*);
public:
  Fl_Slider *CarrierFreq;
private:
  inline void cb_CarrierFreq_i(Fl_Slider*, void*);
  static void cb_CarrierFreq(Fl_Slider*, void*);
public:
  Fl_DrawShape *LfoShape;
  Fl_DrawShape *CarrierShape;
  Fl_Double_Window* stepSequencer();
  Fl_Double_Window *stepSeqWindow;
  Fl_Value_Input *numSteps;
private:
  inline void cb_numSteps_i(Fl_Value_Input*, void*);
  static void cb_numSteps(Fl_Value_Input*, void*);
  inline void cb_Compute_i(Fl_Button*, void*);
  static void cb_Compute(Fl_Button*, void*);
  inline void cb_Exit_i(Fl_Return_Button*, void*);
  static void cb_Exit(Fl_Return_Button*, void*);
  inline void cb_stepLevel_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel(Fl_Value_Slider*, void*);
  inline void cb_stepLevel1_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel1(Fl_Value_Slider*, void*);
  inline void cb_stepLevel2_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel2(Fl_Value_Slider*, void*);
  inline void cb_stepLevel3_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel3(Fl_Value_Slider*, void*);
  inline void cb_stepLevel4_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel4(Fl_Value_Slider*, void*);
  inline void cb_stepLevel5_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel5(Fl_Value_Slider*, void*);
  inline void cb_stepLevel6_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel6(Fl_Value_Slider*, void*);
  inline void cb_stepLevel7_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel7(Fl_Value_Slider*, void*);
  inline void cb_stepLevel8_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel8(Fl_Value_Slider*, void*);
  inline void cb_stepLevel9_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel9(Fl_Value_Slider*, void*);
  inline void cb_stepLevela_i(Fl_Value_Slider*, void*);
  static void cb_stepLevela(Fl_Value_Slider*, void*);
  inline void cb_stepLevelb_i(Fl_Value_Slider*, void*);
  static void cb_stepLevelb(Fl_Value_Slider*, void*);
  inline void cb_stepLevelc_i(Fl_Value_Slider*, void*);
  static void cb_stepLevelc(Fl_Value_Slider*, void*);
  inline void cb_stepLeveld_i(Fl_Value_Slider*, void*);
  static void cb_stepLeveld(Fl_Value_Slider*, void*);
  inline void cb_stepLevele_i(Fl_Value_Slider*, void*);
  static void cb_stepLevele(Fl_Value_Slider*, void*);
  inline void cb_stepLevelf_i(Fl_Value_Slider*, void*);
  static void cb_stepLevelf(Fl_Value_Slider*, void*);
  inline void cb_stepLevel10_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel10(Fl_Value_Slider*, void*);
  inline void cb_stepLevel11_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel11(Fl_Value_Slider*, void*);
  inline void cb_stepLevel12_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel12(Fl_Value_Slider*, void*);
  inline void cb_stepLevel13_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel13(Fl_Value_Slider*, void*);
  inline void cb_stepLevel14_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel14(Fl_Value_Slider*, void*);
  inline void cb_stepLevel15_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel15(Fl_Value_Slider*, void*);
  inline void cb_stepLevel16_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel16(Fl_Value_Slider*, void*);
public:
  Fl_Value_Input *stepDur[24];
  Fl_Value_Slider *stepLevel[24];
private:
  inline void cb_stepLevel17_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel17(Fl_Value_Slider*, void*);
public:
  void customWave();
  Fl_Double_Window *customWavWindow;
private:
  inline void cb_levelHarm_i(Fl_Value_Slider*, void*);
  static void cb_levelHarm(Fl_Value_Slider*, void*);
  inline void cb_levelHarm1_i(Fl_Value_Slider*, void*);
  static void cb_levelHarm1(Fl_Value_Slider*, void*);
  inline void cb_levelHarm2_i(Fl_Value_Slider*, void*);
  static void cb_levelHarm2(Fl_Value_Slider*, void*);
  inline void cb_levelHarm3_i(Fl_Value_Slider*, void*);
  static void cb_levelHarm3(Fl_Value_Slider*, void*);
  inline void cb_levelHarm4_i(Fl_Value_Slider*, void*);
  static void cb_levelHarm4(Fl_Value_Slider*, void*);
public:
  Fl_Value_Input *numHarm[6];
  Fl_Value_Slider *levelHarm[6];
private:
  inline void cb_levelHarm5_i(Fl_Value_Slider*, void*);
  static void cb_levelHarm5(Fl_Value_Slider*, void*);
  inline void cb_Compute1_i(Fl_Button*, void*);
  static void cb_Compute1(Fl_Button*, void*);
  inline void cb_Exit1_i(Fl_Return_Button*, void*);
  static void cb_Exit1(Fl_Return_Button*, void*);
public:
  Fl_Round_Button *radioSine;
  Fl_Round_Button *radioTriangle;
  Fl_Round_Button *radioUpRamp;
  Fl_Round_Button *radioDownRamp;
  Fl_Round_Button *radioSquare;
  Fl_Round_Button *radioLastWave;
  void show();
  void bye();
  virtual void joy_callback();
  virtual void LFO_radio_callback(int i);
  virtual void carrier_radio_callback(int i);
  virtual void carrier_freq_callback();
  virtual void customWave_callback(bool isCarr);
  virtual void stepSequencerCompute();
};
#endif
