// generated by Fast Light User Interface Designer (fluid) version 1.0104

#ifndef LFO6gui_h
#define LFO6gui_h
#include <FL/Fl.H>
#include "PortAudioStuff.h"
#include <FL/Fl_Box.H>
class Fl_DrawShape;
extern void drawWaveform(Fl_DrawShape*);

class Fl_DrawShape : public Fl_Box {
public:
  Fl_DrawShape(int X, int Y, int W, int H, const char *l=0) ;
  float *table;
  long tablen;
  void draw();
};
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Positioner.H>
#include <FL/Fl_Slider.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Value_Slider.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Scroll.H>

class LFO6gui : public PAstuff {
  bool isAudio;
  int tableIndex[3];
public:
  LFO6gui();
  Fl_Double_Window *mainWindow;
private:
  inline void cb_joy_i(Fl_Positioner*, void*);
  static void cb_joy(Fl_Positioner*, void*);
  inline void cb_joy1_i(Fl_Positioner*, void*);
  static void cb_joy1(Fl_Positioner*, void*);
  inline void cb_joy2_i(Fl_Positioner*, void*);
  static void cb_joy2(Fl_Positioner*, void*);
public:
  Fl_Positioner *joy[5];
private:
  inline void cb_joy3_i(Fl_Positioner*, void*);
  static void cb_joy3(Fl_Positioner*, void*);
public:
  Fl_Slider *CarrierFreq;
private:
  inline void cb_CarrierFreq_i(Fl_Slider*, void*);
  static void cb_CarrierFreq(Fl_Slider*, void*);
  inline void cb_chTable_i(Fl_Choice*, void*);
  static void cb_chTable(Fl_Choice*, void*);
  static Fl_Menu_Item menu_chTable[];
  inline void cb_chTable1_i(Fl_Choice*, void*);
  static void cb_chTable1(Fl_Choice*, void*);
  static Fl_Menu_Item menu_chTable1[];
  inline void cb_chTable2_i(Fl_Choice*, void*);
  static void cb_chTable2(Fl_Choice*, void*);
  static Fl_Menu_Item menu_chTable2[];
public:
  Fl_Choice *chTable[4];
private:
  inline void cb_chTable3_i(Fl_Choice*, void*);
  static void cb_chTable3(Fl_Choice*, void*);
  static Fl_Menu_Item menu_chTable3[];
  inline void cb_chOscShape_i(Fl_Choice*, void*);
  static void cb_chOscShape(Fl_Choice*, void*);
  static Fl_Menu_Item menu_chOscShape[];
  inline void cb_chOscShape1_i(Fl_Choice*, void*);
  static void cb_chOscShape1(Fl_Choice*, void*);
  static Fl_Menu_Item menu_chOscShape1[];
  inline void cb_chOscShape2_i(Fl_Choice*, void*);
  static void cb_chOscShape2(Fl_Choice*, void*);
  static Fl_Menu_Item menu_chOscShape2[];
  inline void cb_chOscShape3_i(Fl_Choice*, void*);
  static void cb_chOscShape3(Fl_Choice*, void*);
  static Fl_Menu_Item menu_chOscShape3[];
public:
  Fl_Choice *chOscShape[6];
private:
  inline void cb_chOscShape4_i(Fl_Choice*, void*);
  static void cb_chOscShape4(Fl_Choice*, void*);
  static Fl_Menu_Item menu_chOscShape4[];
  inline void cb_chOscShape5_i(Fl_Choice*, void*);
  static void cb_chOscShape5(Fl_Choice*, void*);
  static Fl_Menu_Item menu_chOscShape5[];
public:
  Fl_DrawShape *tableShape[4];
  Fl_Slider *LFO4freq;
private:
  inline void cb_LFO4freq_i(Fl_Slider*, void*);
  static void cb_LFO4freq(Fl_Slider*, void*);
public:
  void customWave(int index);
  Fl_Double_Window *customWavWindow;
private:
  inline void cb_levelHarm_i(Fl_Value_Slider*, void*);
  static void cb_levelHarm(Fl_Value_Slider*, void*);
  inline void cb_levelHarm1_i(Fl_Value_Slider*, void*);
  static void cb_levelHarm1(Fl_Value_Slider*, void*);
  inline void cb_levelHarm2_i(Fl_Value_Slider*, void*);
  static void cb_levelHarm2(Fl_Value_Slider*, void*);
  inline void cb_levelHarm3_i(Fl_Value_Slider*, void*);
  static void cb_levelHarm3(Fl_Value_Slider*, void*);
  inline void cb_levelHarm4_i(Fl_Value_Slider*, void*);
  static void cb_levelHarm4(Fl_Value_Slider*, void*);
public:
  Fl_Value_Input *numHarm[6];
  Fl_Value_Slider *levelHarm[6];
private:
  inline void cb_levelHarm5_i(Fl_Value_Slider*, void*);
  static void cb_levelHarm5(Fl_Value_Slider*, void*);
  inline void cb_Compute_i(Fl_Button*, void*);
  static void cb_Compute(Fl_Button*, void*);
  inline void cb_Exit_i(Fl_Return_Button*, void*);
  static void cb_Exit(Fl_Return_Button*, void*);
  inline void cb_chPartial_i(Fl_Choice*, void*);
  static void cb_chPartial(Fl_Choice*, void*);
  static Fl_Menu_Item menu_chPartial[];
  inline void cb_chPartial1_i(Fl_Choice*, void*);
  static void cb_chPartial1(Fl_Choice*, void*);
  static Fl_Menu_Item menu_chPartial1[];
  inline void cb_chPartial2_i(Fl_Choice*, void*);
  static void cb_chPartial2(Fl_Choice*, void*);
  static Fl_Menu_Item menu_chPartial2[];
  inline void cb_chPartial3_i(Fl_Choice*, void*);
  static void cb_chPartial3(Fl_Choice*, void*);
  static Fl_Menu_Item menu_chPartial3[];
  inline void cb_chPartial4_i(Fl_Choice*, void*);
  static void cb_chPartial4(Fl_Choice*, void*);
  static Fl_Menu_Item menu_chPartial4[];
public:
  Fl_Choice *chPartial[6];
private:
  inline void cb_chPartial5_i(Fl_Choice*, void*);
  static void cb_chPartial5(Fl_Choice*, void*);
  static Fl_Menu_Item menu_chPartial5[];
  inline void cb_phsHarm_i(Fl_Value_Input*, void*);
  static void cb_phsHarm(Fl_Value_Input*, void*);
  inline void cb_phsHarm1_i(Fl_Value_Input*, void*);
  static void cb_phsHarm1(Fl_Value_Input*, void*);
  inline void cb_phsHarm2_i(Fl_Value_Input*, void*);
  static void cb_phsHarm2(Fl_Value_Input*, void*);
  inline void cb_phsHarm3_i(Fl_Value_Input*, void*);
  static void cb_phsHarm3(Fl_Value_Input*, void*);
  inline void cb_phsHarm4_i(Fl_Value_Input*, void*);
  static void cb_phsHarm4(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *phsHarm[6];
private:
  inline void cb_phsHarm5_i(Fl_Value_Input*, void*);
  static void cb_phsHarm5(Fl_Value_Input*, void*);
public:
  Fl_Double_Window* stepSequencer(int index);
  Fl_Double_Window *stepSeqWindow;
  Fl_Value_Input *numSteps;
private:
  inline void cb_numSteps_i(Fl_Value_Input*, void*);
  static void cb_numSteps(Fl_Value_Input*, void*);
  inline void cb_Compute1_i(Fl_Button*, void*);
  static void cb_Compute1(Fl_Button*, void*);
  inline void cb_Exit1_i(Fl_Return_Button*, void*);
  static void cb_Exit1(Fl_Return_Button*, void*);
  inline void cb_stepLevel_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel(Fl_Value_Slider*, void*);
  inline void cb_stepLevel1_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel1(Fl_Value_Slider*, void*);
  inline void cb_stepLevel2_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel2(Fl_Value_Slider*, void*);
  inline void cb_stepLevel3_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel3(Fl_Value_Slider*, void*);
  inline void cb_stepLevel4_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel4(Fl_Value_Slider*, void*);
  inline void cb_stepLevel5_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel5(Fl_Value_Slider*, void*);
  inline void cb_stepLevel6_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel6(Fl_Value_Slider*, void*);
  inline void cb_stepLevel7_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel7(Fl_Value_Slider*, void*);
  inline void cb_stepLevel8_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel8(Fl_Value_Slider*, void*);
  inline void cb_stepLevel9_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel9(Fl_Value_Slider*, void*);
  inline void cb_stepLevela_i(Fl_Value_Slider*, void*);
  static void cb_stepLevela(Fl_Value_Slider*, void*);
  inline void cb_stepLevelb_i(Fl_Value_Slider*, void*);
  static void cb_stepLevelb(Fl_Value_Slider*, void*);
  inline void cb_stepLevelc_i(Fl_Value_Slider*, void*);
  static void cb_stepLevelc(Fl_Value_Slider*, void*);
  inline void cb_stepLeveld_i(Fl_Value_Slider*, void*);
  static void cb_stepLeveld(Fl_Value_Slider*, void*);
  inline void cb_stepLevele_i(Fl_Value_Slider*, void*);
  static void cb_stepLevele(Fl_Value_Slider*, void*);
  inline void cb_stepLevelf_i(Fl_Value_Slider*, void*);
  static void cb_stepLevelf(Fl_Value_Slider*, void*);
  inline void cb_stepLevel10_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel10(Fl_Value_Slider*, void*);
  inline void cb_stepLevel11_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel11(Fl_Value_Slider*, void*);
  inline void cb_stepLevel12_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel12(Fl_Value_Slider*, void*);
  inline void cb_stepLevel13_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel13(Fl_Value_Slider*, void*);
  inline void cb_stepLevel14_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel14(Fl_Value_Slider*, void*);
  inline void cb_stepLevel15_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel15(Fl_Value_Slider*, void*);
  inline void cb_stepLevel16_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel16(Fl_Value_Slider*, void*);
public:
  Fl_Value_Input *stepDur[24];
  Fl_Value_Slider *stepLevel[24];
private:
  inline void cb_stepLevel17_i(Fl_Value_Slider*, void*);
  static void cb_stepLevel17(Fl_Value_Slider*, void*);
public:
  Fl_Double_Window* adsr(int index);
  Fl_Double_Window *adsrWindow;
  Fl_Value_Slider *sldAttak;
private:
  inline void cb_sldAttak_i(Fl_Value_Slider*, void*);
  static void cb_sldAttak(Fl_Value_Slider*, void*);
public:
  Fl_Value_Slider *sldDecay;
private:
  inline void cb_sldDecay_i(Fl_Value_Slider*, void*);
  static void cb_sldDecay(Fl_Value_Slider*, void*);
public:
  Fl_Value_Slider *sldSustain;
private:
  inline void cb_sldSustain_i(Fl_Value_Slider*, void*);
  static void cb_sldSustain(Fl_Value_Slider*, void*);
public:
  Fl_Value_Slider *sldRelease;
private:
  inline void cb_sldRelease_i(Fl_Value_Slider*, void*);
  static void cb_sldRelease(Fl_Value_Slider*, void*);
public:
  Fl_Value_Slider *sldSustDur;
private:
  inline void cb_sldSustDur_i(Fl_Value_Slider*, void*);
  static void cb_sldSustDur(Fl_Value_Slider*, void*);
public:
  Fl_Value_Slider *sldPauseDur;
private:
  inline void cb_sldPauseDur_i(Fl_Value_Slider*, void*);
  static void cb_sldPauseDur(Fl_Value_Slider*, void*);
  inline void cb_Exit2_i(Fl_Return_Button*, void*);
  static void cb_Exit2(Fl_Return_Button*, void*);
public:
  void show();
  void bye();
  virtual void joy_callback(int i);
  virtual void carrier_freq_callback();
  virtual void lfo4_freq_callback();
  virtual void customWave_callback(int tableIndex);
  virtual void stepSequencerCompute(int tableIndex);
  virtual void adsrCompute(int tableIndex);
  virtual void tableShape_callback(Fl_Choice* o, int tableIndex);
  virtual void oscTable_callback(Fl_Choice* o, int oscIndex);
};
#endif
