// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef playerGUI_h
#define playerGUI_h
#include <FL/Fl.H>
#include "PlayerGUI_prot.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Slider.H>
#include <FL/Fl_Value_Output.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Menu_Bar.H>

class PlayerGUI {
public:
  PlayerGUI();
  Fl_Double_Window *MainWindow;
  Fl_Value_Input *txtStart;
private:
  void cb_txtStart_i(Fl_Value_Input*, void*);
  static void cb_txtStart(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *txtDur;
  Fl_Slider *sldProgressBar;
private:
  void cb_sldProgressBar_i(Fl_Slider*, void*);
  static void cb_sldProgressBar(Fl_Slider*, void*);
public:
  Fl_Value_Output *txtPos;
  Fl_Button *butPlay;
private:
  void cb_butPlay_i(Fl_Button*, void*);
  static void cb_butPlay(Fl_Button*, void*);
public:
  Fl_Button *butStop;
private:
  void cb_butStop_i(Fl_Button*, void*);
  static void cb_butStop(Fl_Button*, void*);
public:
  Fl_Button *butFF;
private:
  void cb_butFF_i(Fl_Button*, void*);
  static void cb_butFF(Fl_Button*, void*);
public:
  Fl_Button *butRew;
private:
  void cb_butRew_i(Fl_Button*, void*);
  static void cb_butRew(Fl_Button*, void*);
public:
  Fl_Box *texFile;
  static Fl_Menu_Item menu_[];
private:
  void cb_Load_i(Fl_Menu_*, void*);
  static void cb_Load(Fl_Menu_*, void*);
  void cb_E_i(Fl_Menu_*, void*);
  static void cb_E(Fl_Menu_*, void*);
public:
  ~PlayerGUI();
  void show();
  bool isPlaying;
  bool isStopped;
  char filename[256];
  Fl_File_Chooser *fc;
  double ffStep;
};
#endif
