# SConstruct for VST plugins
# examples and projects
# (c) V Lazzarini, 2009
# 
# See the end of the file for instructions on
# how to add your own projects

import os
import sys

if sys.platform[:3] == 'win':
   local_path = 'C:/msys/1.0/local'
   env =  Environment(ENV = {'PATH' : os.environ['PATH'],
          'TEMP' : os.environ ['TEMP']}, TOOLS=['mingw']) 
else:
   local_path = '/usr/local'
   env =  Environment(ENV = {'PATH' : os.environ['PATH']})


env.Append(CPPPATH = ['%s/include' % local_path, '.'])
env.Append(LIBPATH = '%s/lib' % local_path)
env.Append(LIBS = 'sndfile')
if sys.platform[:5] == 'linux': env.Append(CPPFLAGS='-D__cdecl=""')
configure = env.Configure()
sane = configure.CheckHeader("stdio.h", language="C")
if not sane:
 print "\n*** BUILD ERROR: there is a problem with your C/C++ compiler"
 print "  =>please check it before proceeding\n"

vstcheck = configure.CheckHeader("vstsdk2.4/pluginterfaces/vst2.x/aeffect.h", language="C++")
if not vstcheck:
  print "\n***BUILD ERROR: VST SDK not found, plugin will not be built"
  print " =>You can get it from"
  print "http://www.steinberg.net/en/company/3rd_party_developer.html"
  print "   please drop the vstsdk2.4 directory here to proceed\n" 

if sane:
 if vstcheck:
  print "*** BUILDING VST plugin *********************"
 print "**********************************************"
 print "NB: you can use the SConstruct file to add your"
 print "own projects to the build. See the SConstruct file"
 print "for further instructions."
 print "***********************************************\n\n"

# VST plugin
if vstcheck:
 vstpath = 'vstsdk2.4/public.sdk/source/vst2.x'
 sdksrcs = ['%s/audioeffect.cpp' % vstpath, 
   	   '%s/audioeffectx.cpp' % vstpath, 
   	   '%s/vstplugmain.cpp' % vstpath]

 env.Append(CPPPATH=['vstsdk2.4', vstpath])
 myplug = env.LoadableModule('plugin',['plugin.cpp', sdksrcs])
 myplug = env.LoadableModule('panner',['panner.cpp', sdksrcs]) 
 myplug = env.LoadableModule('doublepanner',['doublepanner.cpp', sdksrcs]) 
 myplug = env.LoadableModule('eqfil',['eqfil.cpp', sdksrcs])
 myplug = env.LoadableModule('synth',['synth.cpp', sdksrcs])

 if sys.platform[:6] == 'darwin':
   env.Command('plugin.vst/Contents/MacOS/plugin', 'plugin', 
        'cp plugin plugin.vst/Contents/MacOS/plugin');
   env.Command('panner.vst/Contents/MacOS/panner', 'panner', 
        'cp panner panner.vst/Contents/MacOS/panner');
   env.Command('doublepanner.vst/Contents/MacOS/doublepanner', 'doublepanner', 
        'cp doublepanner doublepanner.vst/Contents/MacOS/doublepanner');
   env.Command('eqfil.vst/Contents/MacOS/eqfil', 'eqfil', 
        'cp eqfil eqfil.vst/Contents/MacOS/eqfil');
   env.Command('synth.vst/Contents/MacOS/synth', 'synth', 
        'cp synth synth.vst/Contents/MacOS/synth');

# you can add here your own projects here
# use this format:
# project = env.Program('project', 'source.c')
# where project is the name of your new program 
# and source

