// generated by Fast Light User Interface Designer (fluid) version 1.0104

#include "LFO1gui.h"

inline void LFO1gui::cb_joy_i(Fl_Positioner*, void*) {
  joy_callback();
}
void LFO1gui::cb_joy(Fl_Positioner* o, void* v) {
  ((LFO1gui*)(o->parent()->user_data()))->cb_joy_i(o,v);
}

LFO1gui::LFO1gui():PAstuff() {
  Fl_Window* w;
  { Fl_Window* o = mainWindow = new Fl_Window(385, 454, "a simple LFO example");
    w = o;
    o->user_data((void*)(this));
    { Fl_Positioner* o = joy = new Fl_Positioner(10, 30, 365, 365, "LFO (X controls frequency, Y controls amplitude)");
      o->box(FL_DOWN_BOX);
      o->color(45);
      o->selection_color(1);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(56);
      o->callback((Fl_Callback*)cb_joy);
      o->align(FL_ALIGN_BOTTOM);
      o->when(3);
    }
    { Fl_Value_Input* o = CarrierFreq = new Fl_Value_Input(225, 420, 110, 25, "frequency of the audio carrier:");
      o->maximum(20000);
      o->step(5);
      o->value(220);
      o->align(132);
    }
    make_menu();
    o->end();
    o->resizable(o);
  }
}

void LFO1gui::show() {
  mainWindow->show();
}

void LFO1gui::bye() {
  mainWindow->hide();
}

void LFO1gui::joy_callback() {
}

