// generated by Fast Light User Interface Designer (fluid) version 1.0104

#ifndef LFO2gui_h
#define LFO2gui_h
#include <FL/Fl.H>
#include "PortAudioStuff.h"
#include <FL/Fl_Window.H>
#include <FL/Fl_Positioner.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Round_Button.H>
#include <FL/Fl_Slider.H>

class LFO2gui : public PAstuff {
public:
  LFO2gui();
  Fl_Window *mainWindow;
  Fl_Positioner *joy;
private:
  inline void cb_joy_i(Fl_Positioner*, void*);
  static void cb_joy(Fl_Positioner*, void*);
  inline void cb_Sine_i(Fl_Round_Button*, void*);
  static void cb_Sine(Fl_Round_Button*, void*);
  inline void cb_Triangle_i(Fl_Round_Button*, void*);
  static void cb_Triangle(Fl_Round_Button*, void*);
  inline void cb_Up_i(Fl_Round_Button*, void*);
  static void cb_Up(Fl_Round_Button*, void*);
  inline void cb_Down_i(Fl_Round_Button*, void*);
  static void cb_Down(Fl_Round_Button*, void*);
  inline void cb_Square_i(Fl_Round_Button*, void*);
  static void cb_Square(Fl_Round_Button*, void*);
  inline void cb_Random_i(Fl_Round_Button*, void*);
  static void cb_Random(Fl_Round_Button*, void*);
  inline void cb_Sine1_i(Fl_Round_Button*, void*);
  static void cb_Sine1(Fl_Round_Button*, void*);
  inline void cb_Triangle1_i(Fl_Round_Button*, void*);
  static void cb_Triangle1(Fl_Round_Button*, void*);
  inline void cb_Up1_i(Fl_Round_Button*, void*);
  static void cb_Up1(Fl_Round_Button*, void*);
  inline void cb_Down1_i(Fl_Round_Button*, void*);
  static void cb_Down1(Fl_Round_Button*, void*);
  inline void cb_Square1_i(Fl_Round_Button*, void*);
  static void cb_Square1(Fl_Round_Button*, void*);
  inline void cb_Random1_i(Fl_Round_Button*, void*);
  static void cb_Random1(Fl_Round_Button*, void*);
public:
  Fl_Slider *CarrierFreq;
private:
  inline void cb_CarrierFreq_i(Fl_Slider*, void*);
  static void cb_CarrierFreq(Fl_Slider*, void*);
public:
  void show();
  void bye();
  virtual void joy_callback();
  virtual void LFO_radio_callback(int i);
  virtual void carrier_radio_callback(int i);
  virtual void carrier_freq_callback();
};
#endif
